version: "3.8"

services:
  discord-bot:
    build: .
    container_name: discord-bot-zunami
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - bot_data:/app/data

  cloudflared:
      image: cloudflare/cloudflared:latest
      container_name: zunami-cloudflared
      restart: unless-stopped
      command: tunnel --no-autoupdate run
      environment:
        - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
      depends_on:
        - discord-bot

volumes:
  bot_data:
